galaxy_info:
  author: Ilia Evteev
  description: HW Install Apache on CentOS role

  license: GPL-2.0-or-later

  min_ansible_version: 2.1
 
  platforms:
  - name: CentOS
    versions:
    - 7
    - 8
